trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
     - job: Build
       displayName: Build job
       pool: 
         vmImage: 'ubuntu-latest'
       steps:
       # Task-1: Build Docker Image and push to Azure Container Registry ACR
         - task: Docker@2
           inputs:
             containerRegistry: 'manual-devopsacr-svc'
             repository: 'app1'
             command: 'buildAndPush'
             Dockerfile: '**/Dockerfile'
             tags: 
               $(tag)
        #  # Task-2: Copy kube-manifest files to Build Artifact Directory
        #  - task: CopyFiles@2
        #    inputs:
        #       SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        #       Contents: '**'
        #       TargetFolder: '$(Build.ArtifactStagingDirectory)'
        #       OverWrite: true
   
         # Task 3 publish build artifacts
         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)/kube-manifests'
            ArtifactName: 'kube-manifests'
            publishLocation: 'Container'